services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  gateways:
    image: matheusprotzen/gateways-mock
    ports:
      - "3001:3001"
      - "3002:3002"

  app:
    build: .
    ports:
      - "3333:3333"
